version: '3.8'

services:
  contactcard:
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - 3200:3200
    container_name: contactapp
    image: spygram/contactcardimage:latest
    networks:
      - contact-net

networks:
  contact-net:
    driver: bridge

